version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
           version_number: $CIRCLE_BRANCH
           build_number: $CIRCLE_BUILD_NUM
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          
      - run: npm install
      - run: cd app && sudo npm install -g bower
      - run: cd app && bower cache clean
      - run: cd app && bower install --force 
      - run: sudo npm install -g gulp
      - run: gulp clone-plugins
      - run: gulp packageCorePlugins
      - run: npm run plugin-build
      - run: npm run build
      - run: npm run test
      - store_artifacts:
          path: generic-editor.zip
          destination: generic-editor.zip
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      
                
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
